### ISSUE TITLE
DLQ is not respective of the Message Type

### ISSUE THREAD

**Issue by trevoryager-callaway** [callawaycloud/apex-transactional-outbox#20]
Looks like when you specify a group id for the outbox message, if **any** subscriptions are DLQ’d related to that group id irrespective of the Message Type on the related outbox message, then it will stop ALL subscriptions related to that Group Id from being processed that have been created after the DLQ'd subscription.

DLQ should be organized by Message Type -> Group Id.

**Example:**
Message Definition A
Message Definition B

Outbox Message A created with a group id of 123 and looks up to Message Definition A.
The subscription record related to Outbox Message A enters the DLQ.

Outbox Message B created with a group id of 123 and looks up to Message Definition B.
The subscription record related to Outbox Message B would not be ran because the above subscription record related to Outbox Message A entered the DLQ.

**Comment by trevoryager-callaway** [comment]
May be as simple as updating the Group Id formula on the subscription custom object to:
`IF(ISBLANK(Outbox_Message__r.Group_Id__c), null, Application__c + '-' + Outbox_Message__r.Type__c + '-' + Outbox_Message__r.Group_Id__c)
`

**Comment by trevoryager-callaway** [comment]
Tested an that appears to be the fix

**Comment by ChuckJonas** [comment]
By design (see comment in #21).
